### ISSUE TITLE
ioc.register is not a function

### ISSUE THREAD

**Issue by tinkone** [steve-gray/connect-ioc#3]
I'm getting this `TypeError: ioc.rootContainer.register is not a function`

The code block that I'm using is as follows

```
var ioc = require('connect-ioc');
var instance = ioc();

function test()
{
  console.log( "this is test")
}
ioc.rootContainer.register('injector', test)



```

**Comment by tinkone** [comment]
Perhaps the syntax is wrong, I seem to get pass the error with this

`ioc().rootContainer.register('injector', test)`

`ioc() vs ioc` per documentations.

**Comment by steve-gray** [comment]
Hi Tink,

You're right: on the documentation for usage I've got inadvertently substituted instance and ioc. The correct sequence is:

- var ioc = require('connect-ioc');
- var instance = ioc();
- instance.rootContainer is the root container
- app.use(instance.middleware)

I'll push a github release/npm patch version that contains the correction in the docs.

**Comment by steve-gray** [comment]
@tinkone,

Have fixed the Docs / Pushed update to NPM. If there's any further problems please let me know!

Cheers,
-Steve
